services:
  mysql8:
    image: mysql:8.4.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
#    volumes:
      # 加载初始化脚本
#      - ./scripts/mysql/:/docker-entrypoint-initdb.d/
  redis:
    image: redis:7.4.0
    restart: always
    ports:
      - "6380:6379"
