// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"green/internal/handler"
	"green/internal/ioc"
	"green/internal/service/user"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitMiddlewares()
	userService := service.NewUserService()
	userHandler := handler.NewUserHandler(userService)
	engine := ioc.InitGin(v, userHandler)
	return engine
}
