// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"green/internal/handler"
	"green/internal/ioc"
	"green/internal/repository"
	"green/internal/repository/dao"
	"green/internal/service"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	v := ioc.InitMiddlewares()
	db := InitDB()
	userDao := dao.NewUserDao(db)
	userRepository := repository.NewCachedUserRepository(userDao)
	userService := service.NewUserService(userRepository)
	userHandler := handler.NewUserHandler(userService)
	engine := ioc.InitGin(v, userHandler)
	return engine
}
